# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententry',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
