# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20161121_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpenditure',
            name='document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='upload.Document'),
        ),
    ]
