# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20161121_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpenditure',
            name='month',
            field=models.IntegerField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')]),
        ),
    ]
