# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20161117_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententry',
            name='pre_tax_amount',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='documententry',
            name='tax_amount',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='documententry',
            name='tax_name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
