# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20161117_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpenditures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')])),
                ('year', models.IntegerField()),
                ('monthly_expenditure', models.FloatField(default=None)),
            ],
        ),
    ]
