# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20161118_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyExpenditures',
            new_name='MonthlyExpenditure',
        ),
    ]
